### PR TITLE
Created a CI Test Runner (2)

### PR DESCRIPTION
**Pull request by mtv47**
Removed  KTFmt Check based on @tosigame feedback

### CODE REVIEW

**Review by ForestDope — DISMISSED** [review]
Need to add jacocoReport

**Review by Exino329 — COMMENTED** [review]
testing review comment

**Review by tosigame — CHANGES_REQUESTED** [review]
Incomplete, pls add jacoco.

**Review by tosigame — COMMENTED** [review]
idk yet

**Comment by mtv47** [comment]
Seems like the KTFmt still needs to be performed in order for the tests to run, will add it back

**Comment by mtv47** [comment]
Added SONAR_TOKEN inside of this repository

**Comment by mtv47** [comment]
Turned off Automatic Analysis in Sonar

**Comment by mtv47** [comment]
Sonar failing because the reformatted code is considered as new code and isn't covered by tests, Requesting Reviews nonetheless to merge since the implementation of the CI works

**Comment by mtv47** [comment]
Code smells disappeared from Issues on Sonar, works great and is practical, requesting requests to be closed to see if "Require status checks to pass before merging" works as expected

**Review by tosigame — APPROVED** [review]
great

**Pull request merged**
