### PR TITLE
Added tripids to trip screens

### PR DESCRIPTION
**Pull request by mtv47**
Small changes for futur use

### CODE REVIEW

**Review by tosigame — APPROVED** [review]
Looks good, nothing needs to change!

**Comment by mtv47** [comment]
Forgot about adding tripId to test, my bad

**Review by tosigame — CHANGES_REQUESTED** [review]
Wrong option sry

**Review by mtv47 — COMMENTED** [review]
Timing issues

**Comment by tosigame** [comment]
https://github.com/orgs/community/discussions/37090 , we had this problem, so our approvals were not canceled on commits. Now we fixed it )

**Comment by mtv47** [comment]
Great catch!

**Pull request merged**
