### PR TITLE
Creating trip creation screen with inputs

### PR DESCRIPTION
**Pull request by mtv47**
I've created a simple Trip Creation Screen with the associated view model linked to the TripRepository for firebase access. 

It's missing the functionality of inviting friends because there is some challenges with the fact that the databases stores for now only ids that are hard to get for other users when you are a user. Inviting users by giving them the trip id to enter in the overview is one possible solution that is being discussed but if the team decides that the functionality of inviting should be present in this screen, I will add it in a futur release

### CODE REVIEW

**Review by tosigame — CHANGES_REQUESTED** [review]
Hey, I reviewed your code and it mostly looks good. However, there are some cases where the app can break due to user input. Therefore, you should sanitize the user input data. Also, in the event of incorrect inputs, it would be beneficial to show more information to the users. Additionally, improving and adding some code tests that could fail on bad user input is advisable. Also some refactoring could make the code cleaner and easier to read.

Tests:
1: Add test cases for scenarios when the description is missing to ensure comprehensive test coverage.
2: In CreateTripViewModelTest, check for attribute-level equality rather than object-level to minimize false positives.

CreateTripViewModel:
3: Consider merging CreateTripViewModel with OverviewModel in future releases to reduce ViewModel redundancy.

CreateTrip Screen:
4: Mark the budget field as optional to align with the flexibility in trip planning.
5: Consider making the description field optional, offering users more flexibility.
6: Implement validation to ensure the startDate is before the endDate to prevent planning errors.
7: Ensure error messages are clear and specific to guide users in correcting their input effectively.
8:Validate that the budget, if entered, is a positive number to ensure data integrity. (and a double, not text)
9: Integrate a mini-calendar beside the date input fields in a future release, allowing users a choice in date selection method.
10: Refactor code to separate the Scaffold structure from content logic, improving code maintainability.
11: Move hardcoded UI strings into strings.xml for better localization support and easier maintenance.

**Comment by mtv47** [comment]
For the point 2,  In Kotlin, the == operator is used to compare the equality of two objects in terms of their structural content, not their reference identity

**Comment by mtv47** [comment]
For all the elements that will be addressed later, this was chosen to have a version available for others faster to create/see trips from the emulator to facilitate live testing for PRs that require it

**Review by tosigame — APPROVED** [review]
You solved most of my concerns, and the reasons to not address some of them, are also valid. Great job! Also nice and smart way to handle errors !

**Pull request merged**
